dnd-side-project/dnd-6th-4-ping-pong

app/src/main/res/values/themes.xml
- apply project themes.xml fontFamily
close : #16
=> Feature(font): "Set default font of project"

.idea/misc.xml, app/build.gradle, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/making/InviteDialogFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/making/MakeClassActivity.kt, app/src/main/res/drawable/bg_invite_code.xml, app/src/main/res/drawable/bg_round_dialog.xml, app/src/main/res/drawable/selector_copy_btn.xml, app/src/main/res/layout/activity_make_class.xml, app/src/main/res/layout/fragment_invite_dialog.xml, app/src/main/res/values/strings.xml
- creating InviteDialogFragment and layout
close : #14
=> Design(invite dialog): "Create layout of invite dialog"

app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/LoginActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/LoginViewModel.kt, app/src/main/res/layout/activity_login.xml
-creating layout activity_login.xml
-creating MakeClassActivity, MakeClassViewModel
close : #17
=> Design(Login) : Make layout of MakeClassActivity

app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/lesson/progress/ClassProgressFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/lesson/progress/ClassProgressViewModel.kt, app/src/main/res/drawable/bg_round_white_btn.xml, app/src/main/res/layout/fragment_class_progress.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
1. 홈(수업)의 타임라인이 들어갈 첫 레이아웃을 작성하였음.
2. 그를 위해 필요한 프래그먼트 클래스와 뷰모델을 생성하였음.
close : #31
=> Design(class) : Make ClassProgressFragment layout and viewmodel

app/build.gradle, app/src/main/java/com/dnd/sixth/lmsservice/data/network/ApiService.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/ProvideAPI.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/Url.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/preference/PreferenceManager.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/RepositoryModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/useCase/UseCase.kt, app/src/main/res/layout/fragment_class_progress.xml, build.gradle
1. db 패키지와 domain 패키지를 생성
2. sharedpreference와 retrofit을 사용하기 위한 클래스 및 인터페이스 생성 후 di 처리.
close : #33
=> Feature(createPackage): create Package data and domain

.idea/.name, app/src/main/AndroidManifest.xml, settings.gradle
- project name is changed into 'PingPong'
close : #40
=> Change(project name): "Change name of project"

.idea/misc.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/adapter/viewpager/MainViewPagerAdapter.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/add/ScheduleAddActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/calendar/CalendarFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/calendar/CalendarViewModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/detail/ScheduleDetailActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/detail/ScheduleDetailViewModel.kt, app/src/main/res/layout/activity_calendar.xml, app/src/main/res/layout/activity_schedule_detail.xml, app/src/main/res/values/strings.xml
- Design layout of ScheduleDetailActivity
- change app_name of strings.xml
close : #38
=> Design(detail_schedule): "Design layout of ScheduleDetailActivity"

.idea/misc.xml, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/calendar/CalendarFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/edit/ScheduleEditDialogFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/edit/ScheduleEditViewModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/utility/UnitConverter.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/utility/WindowCompat.kt, app/src/main/res/drawable-v24/bg_round_bottom_sheet_dialog.xml, app/src/main/res/layout/activity_schedule_detail.xml, app/src/main/res/layout/fragment_schedule_edit_dialog.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml, app/src/main/res/values/views.xml
- Design layout of ScheduleEditDialogFragment
- add UnitConverter object class
- add WindowCompat object class
close : #28
=> Design(edit schedule): "Design layout of ScheduleEditDialogFragment"

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/eclipseCodeFormatter.xml, app/src/main/java/com/dnd/sixth/lmsservice/presentation/utility/WindowCompat.kt, formatter/eclipse-java-google-style.xml
- add code formatter file 'eclipse-java-google-style.xml'
close : #46
=> Docs(formatter): "Add Code Formatter File"

.idea/misc.xml, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/calendar/CalendarFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/calendar/FluctuatedDialogFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/schedule/edit/ScheduleEditDialogFragment.kt, app/src/main/res/layout/fragment_fluctuated_dialog.xml
- Design layout of fluctuated schedule notification dialog
close : #45
=> Design(noti dialog): "Design fluctuated notification dialog"

app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/StartFeedBackActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/StartFeedBackViewModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/WriteFeedBackActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/WriteFeedBackViewModel.kt, app/src/main/res/drawable/bg_checkbox_outline_blank.xml, app/src/main/res/drawable/bg_round_white_line_btn.xml, app/src/main/res/drawable/bg_switch_thumb_am_pm.xml, app/src/main/res/drawable/bg_switch_track_am_pm.xml, app/src/main/res/drawable/ic_arrow_back_btn.xml, app/src/main/res/drawable/ic_baseline_access_time_24.xml, app/src/main/res/drawable/ic_baseline_date_range.xml, app/src/main/res/layout/activity_start_feed_back.xml, app/src/main/res/layout/activity_write_feed_back.xml, app/src/main/res/values/switch_style.xml
1. 피드백 시작하기 액티비티와 레이아웃 생성
2. 피드백 작성하기 액티비티와 레이아웃 생성
close #58
=> Design(feedback) : Make layout of FeedBackStart and FeedBackWrite

.idea/misc.xml, app/src/main/res/drawable/ic_all_student.xml, app/src/main/res/layout/activity_schedule_detail.xml, app/src/main/res/layout/fragment_home_calendar.xml, app/src/main/res/layout/item_calendar_student.xml, app/src/main/res/values/strings.xml
- add request button in activity_schedule_detail.xml
close : #71
=> Design(change details): "Add request schedule edition button"

.idea/misc.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/home/classes/calendar/detail/ScheduleDetailActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/home/classes/calendar/detail/request/EditRequestDialogFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/home/classes/calendar/detail/request/EditRequestViewModel.kt, app/src/main/res/layout/activity_schedule_detail.xml, app/src/main/res/layout/fragment_edit_request_dialog.xml, app/src/main/res/layout/fragment_schedule_edit_dialog.xml, app/src/main/res/values/strings.xml
- show the change request dialog when clicking the schedule change request button
close : #72
=> Design(change details): "Create schedule change request dialog"

.idea/misc.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/LoginActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/signup/SignUpActivity.kt, app/src/main/res/drawable-v24/bg_wrong_edittext.xml, app/src/main/res/drawable/bg_checked_box.xml, app/src/main/res/drawable/bg_unchecked_box.xml, app/src/main/res/drawable/ic_baseline_close_24.xml, app/src/main/res/drawable/selector_checkbox_signup.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_sign_up.xml, app/src/main/res/layout/activity_start_feed_back.xml
1. 버튼과 레이아웃 연결
2. 이메일, 비밀번호 유효성 검사 추가
close : #73
=> Design(signup) : Modify Signup layout and Activity

app/build.gradle, app/google-services.json, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/LoginActivity.kt, build.gradle
1. 파이어베이스 콘솔 앱 추가 & 동적 링크 적용
2. json파일(google-services) 추가
close : #91
=> Docs(DynamicLink) : Add Firebase dependencies

.idea/misc.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/data/entity/testEntity/TestHomeworkItem.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/adapter/recyclerAdapter/HomeworkManageAdapter.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/homework/HomeworkManageActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/homework/HomeworkManageViewModel.kt, app/src/main/res/drawable/bg_round_class_numbering.xml, app/src/main/res/layout/activity_homework_manage.xml, app/src/main/res/layout/item_homework_timeline_.xml
1. 타임라인구현을 위한 어답터 추가
2. 숙제관리 레이아웃 생성
close : #99
=> Design(homework) : Make Activity and Adapter and Layout

app/src/main/AndroidManifest.xml
1. manifest에 </activity>가 중복타이핑 된 곳 수정
2. PR 과정에서 conflict를 해결하던 중 실수한 것으로 추정
Resolves : #112
=> Fix(build error) : Fix CI Build error

app/src/main/java/com/dnd/sixth/lmsservice/App.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/model/ClassModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/model/testEntity/TestClassEntity.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/model/testEntity/TestHomeworkItem.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/ApiService.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/api/AuthApi.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/api/ClassApi.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/api/FeedbackApi.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/base/BaseApi.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/base/ProvideAPI.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/base/Url.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/service/AuthService.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/service/ClassService.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/service/FeedbackService.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/preference/PreferenceManager.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/NetworkModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/RepositoryModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/adapter/recyclerAdapter/ClassAdapter.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/adapter/recyclerAdapter/HomeworkManageAdapter.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/adapter/recyclerAdapter/TimeLineAdapter.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/classmanage/calendar/CalendarViewModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/classmanage/classes/ClassViewModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/classmanage/classes/edit/ClassEditActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/classmanage/classes/edit/ClassEditViewModel.kt, app/src/main/res/layout/item_class.xml
- Separation of Retrofit API and Service class
- Separation of network and repository modules
- Add BaseApi class
- Add a package to include the repository interface
Related to : #121
=> Refactor(retrofit): "Separate retrofit api and service class"

app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/classmanage/ClassManageFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/classmanage/calendar/CalendarFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/classmanage/classes/ClassFragment.kt
- Modify the Fragment to change the height of the new Fragment after the observer detects and re-measures the height after the calendar is expanded.
close : #100
=> Fix(main scroll): "Fix an error of the main scroll"

app/src/main/java/com/dnd/sixth/lmsservice/presentation/utility/DateConverter.kt
- Make function of converting date to day of week like '2022-02-22 to 화'
close : #127
=> Feature(date convert): "Convert date to day of week"

app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/data/model/SignUpResponseEntity.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/api/SignApi.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/base/NetworkCommons.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/service/SignService.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/response/User.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/response/UserCreateDto.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/signup/SignUpActivity.kt
1. 회원가입 기능 서버요청 코드 추가중
2. 요청이 실패하는 이슈 발생
fixes : #134
=> Feat(Signup): Feat CreationUser

app/src/main/AndroidManifest.xml
1. http를 사용하여 발생한 문제
2. manifest에 usesCleartextTraffic = true를 추가하여 해결
close : #136
=> Fix(Signup):Fix error Request Signup

app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/LoginActivity.kt
=> Retry Issue 134 commit

app/src/main/java/com/dnd/sixth/lmsservice/data/network/service/SubjectService.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/subject/SubjectRepositoryImpl.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/subject/datasource/remote/SubjectRemoteDataSource.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/subject/datasource/remote/SubjectRemoteDataSourceImpl.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/UseCaseModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/repository/SubjectRepository.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/useCase/DeleteSubjectUseCase.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/base/BaseFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/classmanage/subject/SubjectFragment.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/classmanage/subject/SubjectViewModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/main/classmanage/subject/create/SubjectCreateActivity.kt, app/src/main/res/values/strings.xml
- Delete class by passing class id to query
related to : #149
=> Feature(Delete): "Implement Subject Deletion"

app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/LoginActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/LoginViewModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/signup/SignUpActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/signup/SignUpViewModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/utility/Constants.kt
1. 체크한 상태로 로그인 시 로컬에 이메일 저장되는 형태
2. 회원가입 코드 수정중
close : #146
=> Feature(Login) : Add autoLogin

app/src/main/java/com/dnd/sixth/lmsservice/di/modules/RepositoryModules.kt
=> Fix(CIBUildFail) : Fix Android CI workflow Build Fail

app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/data/mapper/FeedBackCommentMapper.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/model/feedbackComment/CommentModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/model/feedbackComment/FeedBackModel.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/api/FeedbackCommentAPI.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/network/service/FeedBackService.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/FeedBackComment/datasource/FeedBackCommentRepositoryImpl.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/FeedBackComment/datasource/remote/FeedBackCommentRemoteDataSource.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/FeedBackComment/datasource/remote/FeedBackCommentRemoteDataSourceImpl.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/dailyclasstimelist/datasource/remote/DailyClassTimeLineRemoteDataSource.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/dailyclasstimelist/datasource/remote/DailyClassTimeLineTimeLineRemoteDataSourceImpl.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/DataSourceModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/NetworkModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/RepositoryModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/UseCaseModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/entity/CommentEntity.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/entity/FeedBackEntity.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/repository/FeedBackCommentRepository.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/useCase/feedbackComment/UpdateFeedBackUseCase.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/StartFeedBackActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/WriteFeedBackActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/feedback/WriteFeedBackViewModel.kt, app/src/main/res/layout/activity_write_feed_back.xml, app/src/main/res/layout/item_view_homework_list_feedback.xml
1. 현재 api에 숙제 업데이트 기능이 없어서 숙제를 제외한 피드백 내용만 업데이트 가능.
=> Feature(FeedBack) : add UpdateFeedBack of API

app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/UseCaseModules.kt
=> retry clone

app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/data/network/service/FeedBackService.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/FeedBackComment/datasource/FeedBackCommentRepositoryImpl.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/FeedBackComment/datasource/remote/FeedBackCommentRemoteDataSource.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/FeedBackComment/datasource/remote/FeedBackCommentRemoteDataSourceImpl.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/UseCaseModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/repository/FeedBackCommentRepository.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/useCase/feedbackComment/WriteCommentUseCase.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/comment/CommentActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/comment/CommentViewModel.kt, app/src/main/res/layout/activity_comment.xml
=> Feature(Comment) : Add Write Comment API

app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/FeedBackComment/datasource/FeedBackCommentRepositoryImpl.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/FeedBackComment/datasource/remote/FeedBackCommentRemoteDataSource.kt, app/src/main/java/com/dnd/sixth/lmsservice/data/repository/FeedBackComment/datasource/remote/FeedBackCommentRemoteDataSourceImpl.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/UseCaseModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/di/modules/ViewModelModules.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/repository/FeedBackCommentRepository.kt, app/src/main/java/com/dnd/sixth/lmsservice/domain/useCase/feedbackComment/GetCommentFromDailyUseCase.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/comment/CommentActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/comment/check/CheckCommentActivity.kt, app/src/main/java/com/dnd/sixth/lmsservice/presentation/comment/check/CheckCommentViewModel.kt, app/src/main/res/layout/activity_check_comment.xml, app/src/main/res/layout/activity_comment.xml
=> Feature(Comment) : Add Feature Comment Reading

app/src/main/AndroidManifest.xml, app/src/main/java/com/dnd/sixth/lmsservice/presentation/login/signup/SignUpActivity.kt
=> Fix(Signup) : signup_fix
